FROM php-fpm:8.3
RUN apt-get update -y && apt-get install -y openssl zip unzip git
COPY curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html/laravel-pos
COPY . /
EXPOSE 8000
